# Install Packages
- name: Install the rabbitmq server
  yum:
    name: "{{item}}-{{rabbitmq_package_version}}"
    state: latest
  when: ansible_os_family == "RedHat"

- name: Install the rabbitmq server
  yum:
    name: "{{item}}-{{rabbitmq_package_version}}"
    state: latest
  when: ansible_os_family == "RedHat"

- include: configuration.yml

- include: services.yml

- meta: flush_handlers

- include: plugins.yml
- include: vhost.yml
- include: user.yml
- include: policy.yml

- include: sanitycheck.yml
