- name: Download esl-erlang package
  get_url:
    url: wget https://packages.erlang-solutions.com/erlang/esl-erlang/FLAVOUR_1_general/esl-erlang_21.0-1~debian~stretch_amd64.deb
    dest: /home/ansadmin/esl-erlang_21.0-1~debian~stretch_amd64.deb
    owner: admin
    group: admin
    mode: 0755

- name: Install esl-erlang
  yum:
    deb: /home/ansadmin/esl-erlang_21.0-1~debian~stretch_amd64.deb

- name: Download erlang solutions
  get_url:
    url: wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
    dest: /home/ansadmin/erlang-solutions_1.0_all.deb
    owner: admin
    group: admin
    mode: 0755

- name: Install erlang repository
  yum:
    deb: /home/ansadmin/erlang-solutions_1.0_all.deb

- name: Add an Apt signing key
  apt_key:
    url: https://packages.erlang-solutions.com/debian/erlang_solutions.asc
    state: present
    
- name: Ensure erlang is installed.
  package:
    name: erlang
    state: present

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure rabbitmq is started and enabled (if configured).
  service:
    name: "{{ rabbitmq_daemon }}"
    state: "{{ rabbitmq_state }}"
    enabled: "{{ rabbitmq_enabled }}"
